train of pairs: Use block-wise terminology
anr-bmbf-pivot/draft-dns-over-coap pull request #11
Opened 2021-08-30 16:06 UTC by chrysn

"body" and "payload" are distinguished there, as are "operation" and
"exchange"; both explained here briefly.

(As much as I like the train metaphor, there *is* already terminology.)

2021-08-30 18:36 UTC, miri64 requested changes
Mostly wording nits.

2021-08-30 18:36 UTC, miri64 commented on draft-lenders-dns-over-coap.md
> +block-wise is involved.  DNS responses are provided in the body (which is the
```suggestion
block-wise transfer is involved.  DNS responses are provided in the body (which is the
```
?

2021-08-30 18:36 UTC, miri64 commented on draft-lenders-dns-over-coap.md
> +block-wise is involved.  DNS responses are provided in the body (which is the
```suggestion
block-wise is involved.  DNS responses are provided in the body (i.e. the
```
?

2021-08-30 18:36 UTC, miri64 commented on draft-lenders-dns-over-coap.md
> +payload, or the concatenated payloads) of CoAP response. A DoC server MUST
```suggestion
payload, or the concatenated payloads) of a CoAP response. A DoC server MUST
```

or

```suggestion
payload, or the concatenated payloads) of the CoAP response. A DoC server MUST
```

2021-08-31 07:35 UTC, chrysn commented
Thanks, all applied and squashed.

2021-08-31 07:55 UTC, miri64 commented on draft-lenders-dns-over-coap.md
> +payload, or the concatenated payloads) of CoAP response. A DoC server MUST
This one is still there.

2021-08-31 07:55 UTC, waehlisch commented
we should add a reference to the terminology in \S 2. Terminology.

2021-08-31 08:19 UTC, miri64 commented
> we should add a reference to the terminology in \S 2. Terminology.

So something like

> The terms CoAP payload and CoAP body are used as defined in RFC7959.

?

We maybe also should have a closer look into the rest of the text where we use "payload" and actually "body".

2021-08-31 14:07 UTC, chrysn commented on draft-lenders-dns-over-coap.md
> +payload, or the concatenated payloads) of CoAP response. A DoC server MUST
Sorry, committed.

2021-08-31 14:14 UTC, miri64 approved these changes
ACK. Will fix @waehlisch's comment out-of-band.

2021-08-31 14:15 UTC, merged

2021-08-31 14:17 UTC, waehlisch commented
> The terms CoAP payload and CoAP body are used as defined in RFC7959.

use quotation marks ("CoAP payload" and "CoAP body"). otherwise, it is fine.

2021-08-31 14:28 UTC, miri64 commented
> > The terms CoAP payload and CoAP body are used as defined in RFC7959.
> 
> use quotation marks ("CoAP payload" and "CoAP body"). otherwise, it is fine.

See 424aacc

> We maybe also should have a closer look into the rest of the text where we use "payload" and mean actually "body".

Only the request section did it wrong, see 4d9d3b7316724cd6f

2021-08-31 14:31 UTC, miri64 commented
(updated body/payload commit hash in edit)